# Use Node.js LTS version as base image
#FROM node:14 AS build

# Set working directory
#WORKDIR /app

# Copy package.json and package-lock.json
#COPY package*.json ./

# Install dependencies
#RUN npm install

# Copy the rest of the application code
#COPY . .

# Build the Vue.js application
#RUN npm run build

# Use Nginx as the base image for serving the Vue.js application
FROM nginx:alpine

# Copy built Vue.js files to Nginx public directory
#COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
